include ../make_config/Color.mk
include ../make_config/Funcs.mk
include ../make_config/Flags.mk

NAME := ex02_tester
CXXFLAGS += -g3 -std=c++11

SRCS := ex02_tester.cpp

OBJS := $(SRCS:.cpp=.o)

include ../make_config/Recipes.mk
